### ISSUE TITLE
How to exclude files for test

### ISSUE THREAD

**Issue by JiaChen-Zeng** [cfillion/reapack-repository-template#2]
Hi, I want to exclude the reaper project file for test from scanning but upload them to git. Currently they are included, breaking the check action. However, the delopy action is passing.

```
1) Region/jiachen_Make Region Loopable/jiachen_Make Region Loopable.rpp failed:
  missing tag 'version'

Finished checks for 4 packages with 1 failure
Error: Process completed with exit code 1.
```

Also, I would like to know where can I specify the tags for a rpp file.

**Comment by cfillion** [comment]
Create a file named `.reapack-index.conf` with the following contents:

```conf
--ignore "Region/jiachen_Make Region Loopable/jiachen_Make Region Loopable.rpp"
```

**Comment by JiaChen-Zeng** [comment]
Thank you. Though actually I would like to exclude all test files. I wanted to put the test folder in the same folder of the script (ex. for abc.lua, the test folder is abc/abc.rpp), but this is probably difficult to specify. Is this possible?

> Do you want the .RPP to be installable on its own (a Project Templates package) or installed via another package (eg. a script package)?

I think I may use the latter one.

**Comment by cfillion** [comment]
You can also specify to ignore entire directories instead of individual files. Additional files can be added to an existing package using the [`@provides`](https://github.com/cfillion/reapack-index/wiki/Packaging-Documentation#provides) tag. See also [the GUI package editor](https://reapack.com/upload/reascript) as an example (add the files then watch what the generated metadata for it looks like).

**Comment by JiaChen-Zeng** [comment]
Thank you. I think I'll just create a test foler and ignore that folder.
